language: objective-c
osx_image: xcode10

env:
  global:
  - FRAMEWORK_NAME=FlexibleImage
  - PROJECT="FlexibleImage.xcodeproj"
  
  matrix:
    - DESTINATION="OS=5.0,name=Apple Watch Series 4 - 40mm"       TARGET="FlexibleImageWatchOS" PLATFORM="watchOS"
    - DESTINATION="platform=iOS Simulator,OS=12.0,name=iPhone 8"  TARGET="FlexibleImageIOS"     PLATFORM="iOS"
    - DESTINATION="OS=12.0,name=Apple TV"                         TARGET="FlexibleImageTvOS"    PLATFORM="tvOS"
    - DESTINATION="arch=x86_64"                                   TARGET="FlexibleImageMacOS"   PLATFORM="osx"

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - bash update_carthage.sh 0.31.2

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "$PROJECT" -list

  - xcodebuild -project "$PROJECT" -target "$TARGET" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO clean build | xcpretty
  - xcodebuild -project "$PROJECT" -target "$TARGET" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO clean build | xcpretty

before_deploy:
  - carthage build --platform $PLATFORM --no-skip-current --verbose | xcpretty
  - carthage archive $TARGET

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: $TARGET.framework.zip
  skip_cleanup: true
  on:
    repo: kawoou/FlexibleImage
    tags: true
