language: objective-c
osx_image: xcode8

env:
  global:
  - FRAMEWORK_NAME=FlexibleImage

  - PROJECT="FlexibleImage.xcodeproj"
  - IOS_FRAMEWORK_TARGET="FlexibleImageIOS"
  - MACOS_FRAMEWORK_TARGET="FlexibleImageMacOS"
  - TVOS_FRAMEWORK_TARGET="FlexibleImageTvOS"
  - WATCHOS_FRAMEWORK_TARGET="FlexibleImageWatchOS"

  matrix:
    - DESTINATION="OS=2.0,name=Apple Watch - 42mm" TARGET="$WATCHOS_FRAMEWORK_TARGET"

    - DESTINATION="OS=10.3,name=iPhone 7 Plus"     TARGET="$IOS_FRAMEWORK_TARGET"
    - DESTINATION="OS=9.0,name=iPhone 6"           TARGET="$IOS_FRAMEWORK_TARGET"
    - DESTINATION="OS=8.1,name=iPhone 4S"          TARGET="$IOS_FRAMEWORK_TARGET"

    - DESTINATION="OS=10.2,name=Apple TV 1080p"    TARGET="$TVOS_FRAMEWORK_TARGET"
    - DESTINATION="OS=9.0,name=Apple TV 1080p"     TARGET="$TVOS_FRAMEWORK_TARGET"

    - DESTINATION="arch=x86_64"                    TARGET="$MACOS_FRAMEWORK_TARGET"

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - bash update_carthage.sh 0.22

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "$PROJECT" -list

  - xcodebuild -project "$PROJECT" -target "$TARGET" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty
  - xcodebuild -project "$PROJECT" -target "$TARGET" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty

before_deploy:
  - pod lib lint
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: FlexibleImage.framework.zip
  skip_cleanup: true
  on:
    repo: Kawoou/FlexibleImage
    tags: true
